### ISSUE TITLE
http://purecss.io/layouts/gallery/ seems to be broken.

### ISSUE THREAD

**Issue by pmario** [yahoo/pure#552]
- see: http://purecss.io/layouts/gallery/ ... most images can't be loaded. 
- loading the images in the browser creates: access denied. 
- used: FireFox 44, win10

**Comment by lkraav** [comment]
Yeah, looks like the tumblr images have been turned off for some reason.

**Comment by pixeline** [comment]
perhaps using lorempixel.com from now on? You can simply put
 ```html 
<img src="http://lorempixel.com/1200/800/sports/"> 
```
to render a random image about "sports" of dimensions 1200 x 800.

**Comment by radicalbender** [comment]
Also, some of the images on the [grids page](http://purecss.io/grids/) are broken as well. The ones from Instagram are returning a request limit error.

**Comment by redonkulus** [comment]
They are working for me... please re-open if others see the issue.

**Comment by florianjacob** [comment]
Works for me now as well, seems like it was fixed somehow in the meantime…

**Comment by pmario** [comment]
seems to work now. may be addblocker problem. thx

**Comment by radicalbender** [comment]
I'm still seeing an issue on the Grids page. I'm seeing this in the console:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://distilleryimage11.ak.instagram.com/6cb6b5640ddf11e39ff222000aa8009c_7.jpg

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://distilleryimage6.ak.instagram.com/87f1fe8e5afa11e3ab161243c66c91b3_8.jpg

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://distilleryimage5.ak.instagram.com/a30bc212d61711e29ade22000a1f9bd0_7.jpg

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
http://distilleryimage0.ak.instagram.com/ed146454723f11e29f5522000a9f14ae_7.jpg

I disabled Ghostery and uBlock and it's still happening. The first four images load fine, the last four fail every time.

**Comment by redonkulus** [comment]
Its failing for me now too, seems like its an issue with Tumblr. The first 4 pictures are from Flickr, makes sense to just update the broken ones to use Flickr as well. 

I will see if I can get to it soon, otherwise please feel free to provide a PR to fix.
